[package]
name = "trading_system"
version = "0.1.0"
edition = "2021"

[dependencies]
axum ={version = "0.8.1", features = ["macros"]}

tokio = { version = "1", features = ["full"] }

serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"